name: My First Workflow

on: push

jobs: 
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Welcome message
          run: echo "My first Github Actions Job"

        - name: List files
          run: ls
          
        - name: checkout
          run: actions/checkout@v4

        - name: Read files
          run: cat README.md